### ISSUE TITLE
Zperl Profile resetting

### ISSUE THREAD

**Issue by Kithhurrn** [Resike/Z-Perl#109] opened 2023-12-29 13:51 UTC
Problem: I created a Setup profile. I load the profile to any character and Save. I log out and when I log back in Zperl isn't using the Setup profile and I have to reset it everytime.  This has been happening since at least 10.1 with Zperl updated to current releases.

Expected Behavior: Once a profile is loaded and saved for a character Zperl should remember to load that profile and not revert to the Default settings.

I have removed Zperl and all settings for it, reinstalled and this still happens. I've completely reset my WTF and AddOn folders, only installing Zperl and it still happens. While it only takes a few clicks for me to reset to the correct profile this should not be happening to begin with. It annoyed me enough to switch to using ElvUI for most of DF but I don't like ElvUI or I'd have been using it to begin with. Figured I'd switch back to Zperl and am very disappointed that this is still an issue. I also note that some one else also put in a ticket for this same problem back in June 2023 and got no response. Hoping that was just an oversite and I'll have better luck.

**Comment by Sekt0rX** [comment] 2024-02-08 07:14
Confirming this happens to me still too (in SoD at least, haven't tried Retail), also I'll document what seems to be related.

This happens to an extent even with the "default profile" as well. I only use the Raid Frames & the Helper/Assist Frame (the one that shows "Healers Targeting You" etc). The Raid Frames stick but every time I exit/close WoW completely the Assist Frame is back in the center of my screen with the default scale/size, what's interesting is if I /reload it goes back to how I had set it, so every time I start WoW, I have to do /reload.

Even then it's tempramental - If I enable/disable addons (that aren't even related to Z-Pearl) then for some reason it forgets the frame's settings completely and /reload no longer restores it, so I have to set my scale/dimensions/position again.
Which is when I tried creating a profile so I don't have to set it ever again (and I was hoping for no more /reload every time) but the profile doesn't get applied automatically, so for my situation it's still quicker to bind a key to /reload unless I have to change addons, then the custom profile avoids having to redo the settings.

**Comment by Resike** [comment] 2024-02-08 18:58
Because I can't really reproduce this, what does profiles resetting mean? It's always loading with the default settings? Not loading the profile correctly? Certain positions are no loaded?

**Comment by Sekt0rX** [comment] 2024-02-09 01:25
Thanks for looking in to the Assists Frame not saving, it's partially fixed, the Dimensions and the position of the window are now being remembered but the Window Scale is still resetting.

To be clear, the options when resizing the Assists window are:

"Click to Scale Window" = Still Resetting
"Shift+Click to Resize Window" = Now Saving, all good.
The position on the screen is saving now too, all good.

Screenshots:
How I set it before i logout - https://i.imgur.com/BoMVQh9.jpg
When I log back in - https://i.imgur.com/DiFmB1u.jpg

**Comment by Resike** [comment] 2024-02-09 21:38
Will look into that.

**Comment by Resike** [comment] 2024-02-21 22:57
Should be fixed with next release.

**Closed as completed by Resike** 2024-02-21 22:57 UTC
